### ISSUE TITLE
透過色の扱いについて

### ISSUE THREAD

**Issue by ha1f** [SakuragiYoshimasa/Dotkun#10]
@SakuragiYoshimasa 
お絵かきで絵を書いた時、何も描画していない部分は透過色として保存されている
白として扱うか、透過色は透過色にするか

**Comment by ysakuragi16** [comment]
白で良いかと！！

**Comment by ha1f** [comment]
保存するときは透明で、ゲーム時に白にする形でよい？(今後もし分離することがあった時のために）

まあもし透明色っていうのがあったら、透明色ブラシを作らなきゃいけなくて大変だなと思っていたからよかった

**Comment by ysakuragi16** [comment]
これ保存の時点で白にしましょう

**Comment by ha1f** [comment]
loadした画像に透過色があった時に、そこの背景が白になるのがすごく微妙だから、今後は透明色を考えていきたいし、透明は透明で保存させていただきたい・・・
getColorメソッドを、alpha<0.1ならwhiteを返すように修正しますので・・・

**Comment by ysakuragi16** [comment]
了解
