### ISSUE TITLE
TODO:Battleの実装

### ISSUE THREAD

**Issue by ysakuragi16** [SakuragiYoshimasa/Dotkun#4]
- [ ] 敵のDotkunと合った時に同時に攻撃しあって体力を削り合う（相打ちあり）
- [ ] 進行方向に敵がいれば仕掛ける方が先に攻撃して後から相手の攻撃になる(相打ちなし)
- [ ] 進行方向に敵がいればspeedの高い方が先に攻撃して遅い方が後
- [ ] 進行方向に敵がいるDotkunが一方的に攻撃(相打ちなし)
  求む票

**Comment by ha1f** [comment]
```
- [ ] 内容
```
- [ ] 内容

です！

**Comment by ysakuragi16** [comment]
進行方向にいるやつだけに一方的に攻撃に
