### ISSUE TITLE
TODO:Gameの終了判定

### ISSUE THREAD

**Issue by ysakuragi16** [SakuragiYoshimasa/Dotkun#5]

**Comment by ysakuragi16** [comment]
２Dで城のimageを作って、4 \* 4マス分ぐらいの城を置く

**Comment by ysakuragi16** [comment]
あとは場所とimage置く

**Comment by ysakuragi16** [comment]
viewControllerの関数をConrollerから呼び出してるけど絡みすぎ？

**Comment by ha1f** [comment]
コントローラーからならいいんじゃない？

って思ったけどコントローラーってビューコントローラにあるのか

ビューコントローラをコントローラから生成して渡す実装にして、コントローラを完全に上位に持っていかない？

**Comment by ysakuragi16** [comment]
オブザーバーで解決
