### ISSUE TITLE
ゲームのシステムについて

### ISSUE THREAD

**Issue by ha1f** [SakuragiYoshimasa/Dotkun#8]
ゲームの内容に関する相談

**Comment by ha1f** [comment]
- [ ] 敵のDotkunと合った時に同時に攻撃しあって体力を削り合う（相打ちあり）
- [ ] 進行方向に敵がいれば仕掛ける方が先に攻撃して後から相手の攻撃になる(相打ちなし)
- [ ] 進行方向に敵がいればspeedの高い方が先に攻撃して遅い方が後
- [x] 進行方向に敵がいるDotkunが一方的に攻撃(相打ちなし)

**Comment by ysakuragi16** [comment]
敵味方がわかりづらいから体の色だけチームで分ける

**Comment by ysakuragi16** [comment]
今のスピードだと操作が早くて難しいのでもうすこしゲームスピードを遅くすることを考える

**Comment by ysakuragi16** [comment]
基本的に使うアイコンは一つやんな？
過去のはストックしてても

**Comment by ysakuragi16** [comment]
処理重い所なんとかしたいですね

**Comment by ha1f** [comment]
基本使うアイコンは一つ、ModelManagerに持たせた

**Comment by ha1f** [comment]
処理はとりあえずはokなきがするぞ！5sでも動く

**Comment by ysakuragi16** [comment]
初期化のとこいじったのよくなかったで
やっぱ大丈夫

**Comment by ysakuragi16** [comment]
今の感じどう。結構すっきりした

**Comment by ha1f** [comment]
ごめん、よくなかったの・・・？

**Comment by ysakuragi16** [comment]
いや大丈夫！

**Comment by ha1f** [comment]
スッキリした。
マージして大丈夫？
@SakuragiYoshimasa

**Comment by ysakuragi16** [comment]
@ha1fha1f よろしゅう

**Comment by ha1f** [comment]
マージします
UIScreenがきになる(ほかではboundsから計算してる、TabBarの長さは取得してる、statusBarも取得してる)

**Comment by ysakuragi16** [comment]
このissue溜まってきて関係ないこと書いちゃったんで立て直します
